version: '3.5'

services:
  wallet-test:
    image: cryptogarageinc/elements-testing:v0.18.1.3
    container_name: 'wallet-test'
    volumes:
      - "./__tests__/docker-entrypoint.sh:/root/docker-entrypoint.sh"
      - ".:/root/wallet-test/"
    entrypoint: "sh -c \"/root/docker-entrypoint.sh\""