version: '3.5'

services:
  wallet-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./__tests__/docker-entrypoint.sh:/root/docker-entrypoint.sh
      - .:/root/wallet-test
    entrypoint: "sh -c \"/root/docker-entrypoint.sh\""