name: master and develop check

on: 
  push:
    branches:
    - master
    - develop
    - ci_test
    paths-ignore:
    - 'src/consoleCli.js'
    - 'src/debugCli.js'
  pull_request:
    branches:
    - master
    - develop

env:
  DOCKERHUB_VERSION: v0.18.1.3
  GITHUB_VERSION: v0.0.4
  GITHUB_DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository_owner }}/elements-testing-dockerfile/elements-testing
  ENTRYPOINT_PATH: /github/workspace/.github/workflows/docker/test_entrypoint.sh

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login GitHub Registry
      run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull image from GitHub Registry
      run: docker pull ${{ env.GITHUB_DOCKER_IMAGE }}:${{ env.GITHUB_VERSION }}
    - name: init directory
      run: |
        mkdir node_modules
        chmod 777 node_modules
    - name: cache node modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: npm install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: integration test
#      uses: docker://cryptogarageinc/elements-testing:${{ env.DOCKERHUB_VERSION }}
#      with:
#        entrypoint: ${{ env.ENTRYPOINT_PATH }}
      run: |
        docker run -v ${{ github.workspace }}:/github/workspace --entrypoint ${{ env.ENTRYPOINT_PATH }} ${{ env.GITHUB_DOCKER_IMAGE }}:${{ env.GITHUB_VERSION }}
#    - name: after cleanup
#      run: sudo rm -rf bitcoind_datadir
